### ISSUE TITLE
docker-compose and MySQL

### ISSUE THREAD

**Issue by tobyjaguar** [jboss-dockerfiles/business-central#56]
I have taken the mysql example file and added an additional react container. All container build fine, and the business center is available, but it doesn't appear that mysql is being used. I was wondering if there was some additional steps to integrate mysql in this example?

I noticed that the sample-server that is built does not have process capability, which is what I am assuming is the issue. The mysql jbpm db is empty, which I have read would be populated with tables.

Just curious what I would need to do to get this integrated, or where perhaps I have gone astray?

thanks

**Comment by toannhanb7** [comment]
you will need to change `xa-datasource-class` to `com.mysql.cj.jdbc.MysqlXADataSource` in order to make it works with newer MySQL version.

There is still a problem with table engine. Currently, they are using engine `MyISAM` for all tables `Notificaiton_*` which causes error `Specified key was too long; max key length is 1000 bytes` if you are using charset UTF-8. Change it to `ascii` to fix the issue

**Comment by tobyjaguar** [comment]
Thanks for the response. I was having trouble changing the setup of the jBPM configuration and restarting the service from docker, so I went with the Postgre example, which does seem to work out of the box. I will use this if Postgres doesn't fulfill our needs, but so far so good. Thanks again
